version: "3.3"
services:
  poc:
    restart: always
    image: 42-node
    build:
      context: ./
      dockerfile: Dockerfile.42-node
      args:
        - HOST_UID=${HOST_UID-1000}
        - HOST_GID=${HOST_GID-1000}
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    ports:
      - 9229:9229
    networks:
      - mynet
    # command: sh -c 'npm install && npm run start:dev'
    # command: sh -c 'npm install && npm run start:debug
    command: npx tsc -w

networks:
  mynet:
